// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"DemoLayout":{"id":"DemoLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"DemoLayout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'E:/all_projects/vue2-sfc-document/node_modules/.store/dumi@2.2.14/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'E:/all_projects/vue2-sfc-document/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'E:/all_projects/vue2-sfc-document/node_modules/.store/dumi@2.2.14/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'DemoLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-mobile__dist__layouts__DemoLayout" */'E:/all_projects/vue2-sfc-document/node_modules/dumi-theme-mobile/dist/layouts/DemoLayout.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'E:/all_projects/vue2-sfc-document/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'E:/all_projects/vue2-sfc-document/node_modules/.store/dumi@2.2.14/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
