// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'E:/all_projects/vue2-sfc-document/node_modules/dumi-theme-mobile/dist/slots/Device/index.js';
