// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from 'E:/all_projects/vue2-sfc-document/node_modules/.store/dumi@2.2.14/node_modules/dumi/dist/client/theme-api/index.js';
